Repository mribrgr/StuRa-Mitgliederdatenbank, pull requests merged in 2020-07, with the labels that each got.

#99 Fehlende None-Checks, Änderungen am Admin-Panel
  aemter/__init__.py
  aemter/admin.py
  aemter/apps.py
  checklisten/admin.py
  historie/templates/historie/_titleBuilder.html
  historie/templates/historie/modalData/amtModalData.html
  historie/templates/historie/modalData/mitgliedModalData.html
  historie/templates/historie/modalData/userModalData.html
  mitglieder/admin.py
Labels: Bitte prüfen, Entwicklung

#100 Issues during prepareing of presentation
  aemter/admin.py
  importscripts/ReferateUnterbereicheAemter.csv
  importscripts/main.py
  mitglieder/admin.py
  mitglieder/templates/mitglieder/aemter.html
Labels: Verbesserung

#97 Mitgliederverwaltung2
  aemter/migrations/0001_initial.py
  aemter/migrations/0002_auto_20200624_2049.py
  aemter/migrations/0002_auto_20200726_0029.py
  aemter/migrations/0003_auto_20200726_0031.py
  aemter/migrations/0004_auto_20200726_0032.py
  aemter/migrations/0005_auto_20200726_0037.py
  aemter/migrations/0006_auto_20200726_0041.py
  aemter/migrations/0007_auto_20200726_0049.py
  aemter/migrations/0008_auto_20200726_0058.py
  aemter/models.py
  aemter/templates/aemter/department_row.html
  aemter/templates/aemter/main_screen.html
  aemter/views.py
  checklisten/migrations/0001_initial.py
  importscripts/main.py
  mitglieder/forms.py
  mitglieder/funktions.py
  mitglieder/migrations/0001_initial.py
  mitglieder/models.py
  mitglieder/templates/mitglieder/aemter.html
  mitglieder/templates/mitglieder/bereich_dropdown_list_options.html
  mitglieder/templates/mitglieder/mitglied_erstellen_bearbeiten.html
  mitglieder/templates/mitglieder/mitglieder.html
  mitglieder/templates/mitglieder/modal.html
  mitglieder/templates/mitglieder/row.html
  mitglieder/templatetags/__init__.py
  mitglieder/templatetags/mitglieder_extras.py
  mitglieder/tests/test_urls.py
  mitglieder/urls.py
  mitglieder/views.py
  tests/MyFuncAemter.py
  tests/MyFuncMitglieder.py
Labels: Bitte prüfen, Entwicklung

#101 Login und Checklisten dokumentieren
  checklisten/admin.py
  checklisten/models.py
  checklisten/templates/checklisten/_createModal.html
  checklisten/templates/checklisten/main_screen.html
  checklisten/templatetags/t_checklisten/get_perms.py
  checklisten/templatetags/t_checklisten/get_tasks.py
  checklisten/views.py
  docs/sphinx/source/code/checklisten.rst
  docs/sphinx/source/code/historie.rst
  docs/sphinx/source/code/login.rst
  docs/sphinx/source/masterCodeDoc.rst
  login/views.py
Labels: Bitte prüfen, Dokumentation
