Repository mribrgr/StuRa-Mitgliederdatenbank, pull requests merged in 2020-08, with the labels that each got.

#102 Kommando zum Löschen alter Historien-Einträge hinzufügen
  bin/management/__init__.py
  bin/management/commands/__init__.py
  bin/management/commands/delete_old_historie.py
  docs/sphinx/source/code/commands.rst
  docs/sphinx/source/masterCodeDoc.rst
Labels: Bitte prüfen, Entwicklung

#106 Icons für GitHub und Doku
  bin/static/GitHub-Mark-32px.png
  bin/templates/base.html
Labels: Bitte prüfen, Verbesserung

#103 Projektbericht: Aufgaben Benjamin
  .gitignore
  docs/projektbericht/durchfuehrung/images/pull_request_beispiel.png
  docs/projektbericht/durchfuehrung/images/work_item_beispiel.png
  docs/projektbericht/durchfuehrung/implementierung.adoc
  docs/projektbericht/durchfuehrung/wesentliche_entscheidungen.adoc
  docs/projektbericht/ergebnisse/reflexion_benjamin.adoc
  docs/projektbericht/master_durchfuehrung.adoc
  docs/projektbericht/master_ergebnisse.adoc
  docs/projektbericht/master_planung.adoc
  docs/projektbericht/planung/projektorganisation.adoc
Labels: Bitte prüfen, Dokumentation

#111 Fix errors
  aemter/templates/aemter/department_row.html
  aemter/views.py
Labels: Verbesserung

#112 Bugfixes Historie
  docs/sphinx/source/code/commands.rst
Labels: Bitte prüfen, Dokumentation, Entwicklung

#107 Projektbericht lukas
  docs/projektbericht/durchfuehrung/documentation.adoc
  docs/projektbericht/durchfuehrung/test.adoc
  docs/projektbericht/durchfuehrung/uebergabe.adoc
  docs/projektbericht/ergebnisse/reflexion_lukas.adoc
Labels: Dokumentation

#109 Projektbericht Marc
  docs/projektbericht/durchfuehrung/documentation.adoc
  docs/projektbericht/durchfuehrung/entwurf.adoc
  docs/projektbericht/durchfuehrung/test.adoc
  docs/projektbericht/durchfuehrung/uebergabe.adoc
  docs/projektbericht/ergebnisse/reflexion_marc.adoc
  docs/projektbericht/planung/way_of_working.adoc
Labels: Dokumentation

#113 Reflexion Benjamin
  docs/projektbericht/ergebnisse/reflexion_benjamin.adoc
Labels: Bitte prüfen, Dokumentation

#118 Projektbericht-Branch entfernen
  docs/projektbericht/ergebnisse/reflexion_benjamin.adoc
Labels: Dokumentation

#119 Projektbericht mribrgr
  docs/anforderung/README.adoc
  docs/anforderung/files/archit_notebook.adoc
  docs/anforderung/files/iteration-plans/iteration_10_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_11_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_12_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_13_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_14_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_4_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_5_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_6_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_7_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_8_plan.adoc
  docs/anforderung/files/iteration-plans/iteration_9_plan.adoc
  docs/anforderung/files/project_plan.adoc
  docs/anforderung/img/essenceNavigator/2020-02-15.png
  docs/anforderung/img/essenceNavigator/2020-03-01.png
  docs/anforderung/img/essenceNavigator/2020-03-16.png
  docs/anforderung/img/essenceNavigator/2020-04-01.png
  docs/anforderung/img/essenceNavigator/2020-04-16.png
  docs/anforderung/img/essenceNavigator/2020-05-01.png
  docs/anforderung/img/essenceNavigator/2020-05-16.png
  docs/anforderung/img/essenceNavigator/2020-06-01.png
  docs/anforderung/img/essenceNavigator/2020-06-15.png
  docs/anforderung/img/essenceNavigator/2020-07-13.png
  docs/anforderung/img/essenceNavigator/2020-07-20.png
  docs/anforderung/img/essenceNavigator/2020-07-27.png
  docs/anforderung/img/essenceNavigator/2020-08-01.png
  docs/anforderung/img/essenceNavigator/2020-08-02.png
  docs/anforderung/klassendiagramm/diagramm_domain.png
  docs/projektbericht/durchfuehrung/aktivitaeten.adoc
  docs/projektbericht/ergebnisse/reflexion_mauritius.adoc
  docs/projektbericht/planung/ausgangssituation.adoc
Labels: Hilfe gesucht
